### PR TITLE
Hotfix/ssh

### PR DESCRIPTION
**Pull request by SgtMarmite**
- Fixed ssh for MySQL and Postgres
- added sync action tests for ssh

### CODE REVIEW

**Review by davidesner — APPROVED** [review]

**Comment by SgtMarmite** [comment]
Při startupu Postgresu mi lokálně neseběhne ten inicializační skript v image [debezium/example-postgres:2.5.1.Final]

```
2024-09-26 11:07:07 2024-09-26 09:07:07.912 UTC [77] FATAL:  password authentication failed for user "postgres"
2024-09-26 11:07:07 2024-09-26 09:07:07.912 UTC [77] DETAIL:  Role "postgres" does not exist.
2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2024-09-26 11:07:07 2024-09-26 09:07:07.961 UTC [78] FATAL:  password authentication failed for user "postgres"
2024-09-26 11:07:07 2024-09-26 09:07:07.961 UTC [78] DETAIL:  Role "postgres" does not exist.
2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2024-09-26 11:07:07 2024-09-26 09:07:07.979 UTC [79] FATAL:  password authentication failed for user "postgres"
2024-09-26 11:07:07 2024-09-26 09:07:07.979 UTC [79] DETAIL:  Role "postgres" does not exist.
2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2024-09-26 11:07:07 2024-09-26 09:07:07.998 UTC [80] FATAL:  password authentication failed for user "postgres"
2024-09-26 11:07:07 2024-09-26 09:07:07.998 UTC [80] DETAIL:  Role "postgres" does not exist.
2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2024-09-26 11:07:08 2024-09-26 09:07:08.444 UTC [81] ERROR:  schema "inventory" does not exist at character 16
2024-09-26 11:07:08 2024-09-26 09:07:08.444 UTC [81] STATEMENT:  
2024-09-26 11:07:08 
```

Tenhle problém jsem už měl předtím, a nepodařilo se mi ho odstranit. Dle všeho to ale v Githubu funguje a pravděpodobně asi i u tebe, že? @davidesner

**Comment by davidesner** [comment]
> Při startupu Postgresu mi lokálně neseběhne ten inicializační skript v image [debezium/example-postgres:2.5.1.Final]
> 
> ```
> 2024-09-26 11:07:07 2024-09-26 09:07:07.912 UTC [77] FATAL:  password authentication failed for user "postgres"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.912 UTC [77] DETAIL:  Role "postgres" does not exist.
> 2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.961 UTC [78] FATAL:  password authentication failed for user "postgres"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.961 UTC [78] DETAIL:  Role "postgres" does not exist.
> 2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.979 UTC [79] FATAL:  password authentication failed for user "postgres"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.979 UTC [79] DETAIL:  Role "postgres" does not exist.
> 2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.998 UTC [80] FATAL:  password authentication failed for user "postgres"
> 2024-09-26 11:07:07 2024-09-26 09:07:07.998 UTC [80] DETAIL:  Role "postgres" does not exist.
> 2024-09-26 11:07:07     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
> 2024-09-26 11:07:08 2024-09-26 09:07:08.444 UTC [81] ERROR:  schema "inventory" does not exist at character 16
> 2024-09-26 11:07:08 2024-09-26 09:07:08.444 UTC [81] STATEMENT:  
> 2024-09-26 11:07:08 
> ```
> 
> Tenhle problém jsem už měl předtím, a nepodařilo se mi ho odstranit. Dle všeho to ale v Githubu funguje a pravděpodobně asi i u tebe, že? @davidesner

Jj me to funguje normalne i lokalne

**Comment by SgtMarmite** [comment]
@davidesner dodělal jsem https://keboola.atlassian.net/browse/CFT-2942
Přidal jsem tam inicializaci ssh connection přes paramiko, protože ten SSHTunnelForwarder neumožňuje nastavit timeout.

**Review by davidesner — APPROVED** [review]
good!

**Pull request merged**
